# Generated by Django 2.1.7 on 2019-04-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ano', models.CharField(max_length=100)),
                ('Sname', models.CharField(max_length=250)),
                ('Sphoto', models.ImageField(upload_to='all_covers/')),
                ('Fname', models.CharField(max_length=250)),
                ('Fphoto', models.ImageField(upload_to='all_covers/')),
                ('Mname', models.CharField(max_length=250)),
                ('Mphoto', models.ImageField(upload_to='all_covers/')),
                ('School', models.CharField(max_length=500)),
                ('Grade', models.CharField(max_length=100)),
                ('PYmarks', models.ImageField(upload_to='all_covers/')),
                ('PPYmarks', models.ImageField(upload_to='all_covers/')),
                ('Marks', models.CharField(max_length=100)),
                ('Incomecert', models.ImageField(upload_to='all_covers/')),
                ('Foccup', models.CharField(max_length=100)),
                ('Moccup', models.CharField(max_length=100)),
                ('Sfee', models.CharField(max_length=100)),
                ('Scholar', models.CharField(max_length=100)),
            ],
        ),
    ]
